import { Block, BlockTitle, Button, Card, List, ListItem, Progressbar, Radio } from 'konsta/react';
import { useNavigate } from 'react-router-dom';
import { activeLoan, money } from '../data/mock.js';
import { StatusBadge } from '../components/common/UI.jsx';

export function KYCPage(){return <><Block strong inset><StatusBadge tone="success">Verified</StatusBadge><h1 className="text-xl font-bold">Identity verification</h1><p className="text-slate-500">Your identity has been verified.</p></Block><BlockTitle>Verification checklist</BlockTitle><List strong inset><ListItem title="Identity document" after={<StatusBadge tone="success">Verified</StatusBadge>}/><ListItem title="Selfie verification" after={<StatusBadge tone="success">Verified</StatusBadge>}/><ListItem title="Personal information" after={<StatusBadge tone="success">Verified</StatusBadge>}/></List></>}
export function LoanStatusPage(){const navigate=useNavigate();return <><Block strong inset className="text-center"><StatusBadge>Under review</StatusBadge><h1 className="mt-3 text-xl font-bold">Application LN-20261017</h1><p className="text-sm text-slate-500">We are reviewing your application.</p></Block><BlockTitle>Application timeline</BlockTitle><List strong inset><ListItem title="Application submitted" subtitle="17 Oct 2026 · Completed" after="✓"/><ListItem title="Identity verification" subtitle="Completed" after="✓"/><ListItem title="Credit review" subtitle="In progress" after={<StatusBadge>Now</StatusBadge>}/><ListItem title="Approval" subtitle="Waiting"/></List><Block className="action-bar"><Button large rounded onClick={()=>navigate('/loan/active')}>View active loan</Button></Block></>}
export function LoanDetailPage(){const navigate=useNavigate();return <><Block strong inset><div className="flex justify-between"><div><p className="m-0 text-sm text-slate-500">Outstanding</p><h1 className="m-0 text-3xl font-bold">{money(activeLoan.outstanding)}</h1></div><StatusBadge tone="success">Active</StatusBadge></div><Progressbar progress={activeLoan.progress} className="mt-5"/><div className="mt-2 flex justify-between text-xs text-slate-500"><span>{activeLoan.progress}% paid</span><span>{activeLoan.tenor} months</span></div></Block><BlockTitle>Loan information</BlockTitle><List strong inset><ListItem title="Principal" after={money(activeLoan.principal)}/><ListItem title="Interest rate" after={`${activeLoan.rate}% / month`}/><ListItem title="Next payment" after={money(activeLoan.nextPayment)}/><ListItem title="Due date" after={activeLoan.dueDate}/></List><BlockTitle>Installment schedule</BlockTitle><List strong inset className="!mb-8"><ListItem title="Installment 1" subtitle="Paid" after="✓"/><ListItem title="Installment 2" subtitle="Due" after={money(activeLoan.nextPayment)}/><ListItem title="Installment 3" subtitle="Upcoming"/></List><Block className="action-bar"><Button large rounded onClick={()=>navigate('/repayment')}>Make repayment</Button></Block></>}
export function RepaymentPage(){const navigate=useNavigate();return <><Block strong inset className="text-center"><p className="m-0 text-sm text-slate-500">Amount due</p><h1 className="text-3xl font-bold">{money(activeLoan.nextPayment)}</h1><p className="text-sm text-slate-500">Due {activeLoan.dueDate}</p></Block><BlockTitle>Payment method</BlockTitle><List strong inset><ListItem title="Bank transfer" media={<Radio name="method" checked readOnly/>} subtitle="BCA virtual account"/><ListItem title="Online payment" media={<Radio name="method" readOnly/>} subtitle="Available payment providers"/></List><Block className="action-bar"><Button large rounded onClick={()=>navigate('/payment')}>Continue payment</Button></Block></>}
export function PaymentDetailPage(){const navigate=useNavigate();return <><Block strong inset className="text-center"><div className="success-icon" aria-hidden="true">✓</div><StatusBadge tone="success">Payment successful</StatusBadge><h1 className="text-xl font-bold">{money(activeLoan.nextPayment)}</h1><p className="text-sm text-slate-500">Payment reference PAY-20261020</p></Block><BlockTitle>Payment details</BlockTitle><List strong inset className="!mb-8"><ListItem title="Date" after="20 Oct 2026"/><ListItem title="Method" after="Bank transfer"/><ListItem title="Loan" after={activeLoan.id}/></List><Block><Button large rounded outline onClick={()=>navigate('/loan/active')}>Back to loan</Button></Block></>}
